# Generated by Django 5.0.3 on 2024-03-21 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 5, 13, 9, 733547, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
